# Generated by Django 3.2.5 on 2021-11-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.CharField(max_length=200, verbose_name='Descricao')),
                ('deadline', models.DateField(verbose_name='Prazo Final')),
                ('type', models.CharField(max_length=30, verbose_name='Tipo')),
                ('status', models.CharField(blank=True, choices=[('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Em andamento', max_length=20, null=True, verbose_name='Status')),
                ('doc', models.FileField(upload_to='docs', verbose_name='Documentos')),
                ('repository', models.CharField(max_length=100, verbose_name='Repositorio')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
                'ordering': ['id'],
            },
        ),
    ]
