# Generated by Django 3.2.5 on 2021-11-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='doc',
        ),
    ]
